### PR TITLE
Fixed some bugs (see commit details and implementation for details)

### PR DESCRIPTION
**Pull request by Syqinx**
已更正代码中的一些bug，请审查

### CODE REVIEW

**Comment by ShichangZh** [comment]
Thank you so much for bringing up these issues and providing potential solutions to help improve our code quality. I have a few comments.

1. For the output_path, it is indeed a bug when special parameters like feature_noise are set and num_exp > 1. Thank you for catching it. However, regarding the fix, I would prefer accessing `num_exp` inside the run function with `args.num_exp` instead of adding an extra argument to the run function. This will keep the function arguments clean.
2. For the implementation of the `rand_train_test_idx` function. I think there could be a mismatch between the intended non-negative node index and the actual non-negative node index when ignore_negative is set to true, as `label = label[label >= 0]` changes all the node indices without mapping them back.
3. What are these `.idea/` files for?

Please kindly let me know whether you would agree with these comments.

**Comment by Syqinx** [comment]
1. Yes! You are right, but I think the parameter `args.seed` is a better choise, Because `args.num_exp` does not represent the current state of the experiment, it is just a number that specifies the number of times the experiment is performed.
2. Yes! Thank you for your correction!
3. `.idea/` folder was added automatically when I imported the project into IDE-PyCharm, and I forgot to exclude it from the `.gitignore` file.

**Comment by Syqinx** [comment]
@ShichangZh

**Comment by ShichangZh** [comment]
Thank you for the quick update. I agree that using `args.seed` is a more reasonable choice for the first point. For the second point of the `rand_train_test_idx` function, a minor comment is that the variable name `valid_idx` is overloaded for "valid (nonnegative) labels" and "labels for validation". Maybe the first `valid_idx` in line 253 can be renamed to something like `nonnegative_idx` to avoid confusion?

**Comment by ShichangZh** [comment]
The fix looks good to me. I think this pull request can be merged. @nshah171

**Pull request merged**
